<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<testng-results failed="1" passed="0" skipped="0" total="1">
    <suite duration-ms="11129" name="io.cucumber.core.plugin.TestNGFormatter">
        <test duration-ms="11129" name="io.cucumber.core.plugin.TestNGFormatter">
            <class name="Admin process on blogs app">
                <test-method duration-ms="22" finished-at="2022-10-29T09:37:05.430868Z" name="Admin Add New Blog Without Image" started-at="2022-10-29T09:37:05.222620Z" status="FAIL">
                    <exception class="io.cucumber.core.exception.CucumberException">
                        <message><![CDATA[Given the user logged in as "admin".........................................failed
And the browser opened at "/"...............................................skipped
When the user action on "More"..............................................skipped
]]></message>
                        <full-stacktrace><![CDATA[io.cucumber.core.exception.CucumberException: Failed to instantiate class metafox.stepdefs.GivenStepDefinitions
	at io.cucumber.core.backend.DefaultObjectFactory.cacheNewInstance(DefaultObjectFactory.java:67)
	at io.cucumber.core.backend.DefaultObjectFactory.getInstance(DefaultObjectFactory.java:45)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:85)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:84)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:129)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:129)
	at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
	at metafox.CucumberTestRunner.feature(CucumberTestRunner.java:71)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)
	at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:17)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at io.cucumber.core.backend.DefaultObjectFactory.cacheNewInstance(DefaultObjectFactory.java:53)
	... 30 more
Caused by: java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases
	at org.openqa.selenium.internal.Require$StateChecker.nonNull(Require.java:311)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:135)
	at org.openqa.selenium.firefox.GeckoDriverService.access$100(GeckoDriverService.java:45)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.findDefaultExecutable(GeckoDriverService.java:181)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:437)
	at org.openqa.selenium.firefox.GeckoDriverService.createDefaultService(GeckoDriverService.java:94)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:99)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:95)
	at metafox.webdriver.WebDriverFactory.createLocalFireFox(WebDriverFactory.java:112)
	at metafox.webdriver.WebDriverFactory.createWebDriverForPlatform(WebDriverFactory.java:77)
	at metafox.webdriver.ManagedWebDriver.getWebDriver(ManagedWebDriver.java:28)
	at metafox.CucumberTestRunner.getWebDriver(CucumberTestRunner.java:56)
	at metafox.pageobjects.Components.<init>(Components.java:31)
	at metafox.stepdefs.GivenStepDefinitions.<init>(GivenStepDefinitions.java:40)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	... 33 more
]]></full-stacktrace>
                    </exception>
                </test-method>
            </class>
        </test>
    </suite>
</testng-results>
